import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import { ThemeProvider } from "next-themes";
import Sidebar from "./components/sidebar";
import Providers from "./redux/providers";
import SidebarToggle from "./components/sidebar/sidebarToggle";

const geistJakarta = Plus_Jakarta_Sans({
  variable: "--font-geist-jakarta",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistJakarta.variable} antialiased`}>
        <Providers>
          <ThemeProvider attribute="class" defaultTheme="light">
            <Sidebar />
            <SidebarToggle />
            <main className="grow  h-[120vh]">
              <Header />
              {children}
            </main>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
