import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Header from "./components/header/index";
import { ThemeProvider } from "next-themes";
import Sidebar from "./components/sidebar";
import Providers from "./redux/providers";
import SidebarToggle from "./components/sidebar/sidebarToggle";
import Modal from "./components/modal";
import { ToastContainer } from "react-toastify";

const geistJakarta = Plus_Jakarta_Sans({
  variable: "--font-geist-jakarta",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistJakarta.variable} antialiased`}>
        <Providers>
          <ThemeProvider attribute="class" defaultTheme="light">
            <Header />
            <SidebarToggle />
            <main className=" flex h-[calc(100vh-83.83px)]">
              <Sidebar />
              <div className=" flex-1 bg-LightGreyBG  dark:bg-VeryDarkGrey overflow-hidden">
                {children}
              </div>
            </main>
            <Modal />
            <ToastContainer
              position="bottom-right"
              autoClose={2000}
              theme="light"
            />
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
